### ISSUE TITLE
>12 Datastores

### ISSUE THREAD

**Issue by clemone210** [aseques/nimble_storage_zabbix#1]
Could you guide how to extend the template for a use case of for example 30 datastores?

**Comment by aseques** [comment]
There are three metrics I'm getting are volSizeHigh, volUsageLow and percentage Vol, you can create new entries adding this in the yml file (replace XX for the index number of the OID)
To avoid getting warnings about the duplicate uuid I used the details [here](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/450493-uuid-when-importing-new-items)


```
        - uuid: 59f7405830e145d3a17cab3656fa22bb
          name: 'volSizeHigh XX'
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.37447.1.2.1.5.XX
          key: NIMBLE-MIB.volSizeHigh.XX
          history: 7d
          trends: '0'
          status: DISABLED
          description: 'Maximum defined size of a volume in bytes - high order bytes.'
          
        - uuid: 649906b02c1940fb8a0c9bee6bd82705
          name: 'volUsageLow XX'
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.37447.1.2.1.6.XX
          key: NIMBLE-MIB.volUsageLow.XX
          history: 7d
          trends: '0'
          units: B
          description: 'Current number of bytes a volume is using - low order bytes.'
          preprocessing:
            - type: MULTIPLIER
              parameters:
                - '1048576'
                
        - uuid: 925ee9eae6284177abf7122a5b95a560
          name: 'percentage VolXX'
          type: CALCULATED
          key: percentageVolXX
          units: '%'
```
